### ISSUE TITLE
Installing SSHD inside container  for condor_submit -i support

### ISSUE THREAD

**Issue by khurtado** [opensciencegrid/osgvo-tensorflow-gpu#5]
Hello,

Since HTCondor 8.6.11, it is possible to `condor_ssh_to_job` and use `condor_submit -i` with singularity containers. We would like to have this feature to access resources with available GPUs interactively via condor in CMS [1]. This requires `sshd` to be installed inside the container. Could that be installed?

[1] https://ggus.eu/index.php?mode=ticket_info&ticket_id=136919

**Comment by efajardo** [comment]
@rynge added openssh so we can close this one.
